# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResizedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_field_name', models.CharField(max_length=80)),
                ('source_id', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('actual_width', models.IntegerField(blank=True, null=True)),
                ('actual_height', models.IntegerField(blank=True, null=True)),
                ('format', models.IntegerField(choices=[(1, b'JPEG'), (2, b'PNG'), (3, b'GIF')], default=1)),
                ('quality', models.IntegerField(blank=True, null=True)),
                ('should_crop', models.BooleanField(default=False)),
                ('image', models.FileField(blank=True, upload_to=b'resized/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
    ]
